version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: coygo/node-aws-docker-compose
    environment:
      - NODE_VER: "8114"
      - AWS_CLI_VER: "11619"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build image
          command: docker-compose build
      - run:
          name: Push the docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
               docker login -u $DOCKER_USER -p $DOCKER_PASS

               docker tag coygo/node-aws-docker-compose:latest coygo/node-aws-docker-compose:node.$NODE_VER.aws.$AWS_CLI_VER

               docker push coygo/node-aws-docker-compose:node.$NODE_VER.aws.$AWS_CLI_VER
               docker push coygo/node-aws-docker-compose:latest
            else
              echo "not pushing an image since we are on a branch"
            fi
