version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: lunafi/slim-meteord
    environment:
      - NODE_VER: "893"
      - AWS_CLI_VER: "11416"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: build image
          command: docker-compose build
      - run:
          name: Push the docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
               docker login -u $DOCKER_USER -p $DOCKER_PASS

               docker tag lunafi/slim-meteord:latest lunafi/slim-meteord:node.$NODE_VER.aws.$AWS_CLI_VER

               docker push lunafi/slim-meteord:node.$NODE_VER.aws.$AWS_CLI_VER
               docker push lunafi/slim-meteord:latest
            else
              echo "not pushing an image since we are on a branch"
            fi